// <auto-generated />
namespace BSCS_32E1_HOSPITAL_MANAGEMENT_SYSTEM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addAmbulanceDriversInDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAmbulanceDriversInDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201811181336425_addAmbulanceDriversInDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
